project:
  type: book

book:
  title: "Database Notes"
  author: "Kittipos Sirivongrungsone"
  date: today
  repo-url: https://github.com/Lightbridge-KS/db-notes
  site-url: https://db-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: DB
      chapters: 
        - "contents/concept/db-01-organization.qmd"
        - "contents/concept/db-02-mssql-server.qmd"
    - part: SQL
      chapters: 
        - "contents/sql/sql-01-quickstart.qmd"
        - "contents/sql/sql-02-sqlite-query.qmd"
        - "contents/sql/sql-03-ms-sql-query.qmd"


bibliography: references.bib

format:
  html:
    theme:
      light:
      - cosmo
      - brand
      dark: 
      - darkly
    toc-depth: 4


freeze: auto


